# Tensorflow Graph

In [1]:
# For Jupyter autocompletion
# Tabnine::config

import tensorflow as tf
tf.__version__

'2.4.1'

In [26]:
# tf1
# tf.get_default_graph()
# tf2
tf.compat.v1.get_default_graph()

In [27]:
graph1 = tf.Graph()
graph1.as_default()

In [28]:
graph2 = tf.Graph()
graph2

In [29]:
graph3 = tf.Graph()
graph3

In [31]:
with graph1.as_default():
    print(graph1 is tf.compat.v1.get_default_graph())

True


In [32]:
print(graph1 is tf.compat.v1.get_default_graph())

False



# Variables and placeholders

Variables: hold the values. need to be initialized in the session.
Placeholders: initially empty. We should feed in the data into them. Need expected tensorflow datatypes and can have shape argument.


In [37]:
tensor1 = tf.random.uniform((4,4), 0, 1)
tensor1

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.2008655 , 0.5596622 , 0.49625957, 0.9705584 ],
       [0.6776197 , 0.36149585, 0.63713145, 0.26829147],
       [0.8651694 , 0.97938037, 0.13871694, 0.7339916 ],
       [0.7316948 , 0.8138089 , 0.95138717, 0.63859653]], dtype=float32)>

In [38]:
variable1 = tf.Variable(initial_value=tensor1)
variable1

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[0.2008655 , 0.5596622 , 0.49625957, 0.9705584 ],
       [0.6776197 , 0.36149585, 0.63713145, 0.26829147],
       [0.8651694 , 0.97938037, 0.13871694, 0.7339916 ],
       [0.7316948 , 0.8138089 , 0.95138717, 0.63859653]], dtype=float32)>

In tensorflow1, you need to initialize your variable initializer at the begining of the session. 

In [40]:
# tf1 
# init = tf.global_variables_initializer
# with tf.session() as sess:
#     sess.run(init)

placeholder exist in TF1, but not in tf2. because it is simply not compatible with the eager execution mode. you should either use it with the compatibility API or just don't use them! It used to be define as:

placeholder1 = tf.Placeholder(tf.float32, shape = (4,4))

https://www.tensorflow.org/guide/migrate
There's no usage of sessions or placeholders.