In [1]:
# TF basics 1
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

# TF1 vs TF2 

tensorflow 2 is by default in eager execution mode while tensorflow1 is not. To print a constant in tensorflow 1, you need a tf.Session() while for tf 2, you simply use tf.print.

In [9]:
hello = tf.constant("Hello ")
world = tf.constant("World")

In [10]:
tf.print(hello)

Hello 


In [11]:
tf.print(hello+world)

Hello World


In [12]:
a = tf.constant(1)

In [13]:
b = tf.constant(2)

In [15]:
# again, in tf1 you get type ops.Tensor while in tensorflow2 you get the eager tensor.
type(a)

tensorflow.python.framework.ops.EagerTensor

In [19]:
tf.print(a+b)

3


In [23]:
fill_mat = tf.fill((4,4), 1)
fill_mat

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

In [22]:
fill_zeros = tf.zeros((4,4))
fill_zeros

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [27]:
# tf1 = random_normal
fill_rand_normal = tf.random.normal((4,4), mean=0, stddev=1.0)
fill_rand_normal

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.15616064, -0.5532463 , -0.03943237,  0.32716155],
       [ 1.4482397 , -0.5322301 ,  1.6237153 , -1.6458195 ],
       [-2.6940103 ,  0.4061563 ,  0.12338038,  0.43604782],
       [ 0.79462063, -1.4722733 ,  0.9518234 ,  0.88933116]],
      dtype=float32)>

In [29]:
fill_rand_uniform = tf.random.uniform((4,4), minval=0, maxval=1)
fill_rand_uniform

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.6238215 , 0.467721  , 0.04259872, 0.8310926 ],
       [0.5965407 , 0.58184326, 0.76275146, 0.78428197],
       [0.7524179 , 0.896286  , 0.3123852 , 0.05864167],
       [0.10502088, 0.2617513 , 0.19812036, 0.22330427]], dtype=float32)>

# Metrics multiplication

In [35]:
t1 = tf.constant([ [1,2],
                   [3,4] ])
tf.shape(t1)

# in TF1: t1.getshape() 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [38]:
t2 = tf.constant([ [10], [100] ])
tf.shape(t2)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 1], dtype=int32)>

In [40]:
multiplication = tf.matmul(t1,t2)
multiplication

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[210],
       [430]], dtype=int32)>